services:
  - type: web
    name: email-contact-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
      # Set these in Render Dashboard after deploy or here if not secret
      # - key: SMTP_HOST
      #   value: smtp.example.com
      # - key: SMTP_PORT
      #   value: 587
      # - key: SMTP_SECURE
      #   value: false
      # - key: SMTP_USER
      #   sync: false
      # - key: SMTP_PASS
      #   sync: false
      # - key: FROM_EMAIL
      #   value: no-reply@tinfo.space
      # - key: TO_EMAIL
      #   value: feedback@tinfo.space
      # - key: ALLOWED_ORIGINS
      #   value: https://<your-gh-user>.github.io
